settings_version: 0.0.4
datasets_dir: .\
weights_dir: weights
runs_dir: runs
uuid: 54bc643a09dab05e0ee2875ca62f44db0afac9f1cb4a63b6c902c48936dcc8fc
sync: true
api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
